# Generated by Django 3.2.5 on 2022-04-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0002_auto_20220402_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_account',
            old_name='customer_id',
            new_name='user_id',
        ),
    ]
